* mksp-pkg-0.0.5 : added support for _mksp_pkg_* commands
* mksp-raw-0.0.4  : added support for _mksp_raw_* commands and ~/.flxdefaults
* flxrescan-0.0.4 : speedups by eliminating some fork-execs

diff --git a/build/mksp-pkg b/build/mksp-pkg
--- a/build/mksp-pkg
+++ b/build/mksp-pkg
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# mksp-pkg - make a pkg dir from several softwares - version 0.0.4 - 2005-11-01
+# mksp-pkg - make a pkg dir from several softwares - version 0.0.5 - 2006-01-27
 # This file is part of the Formilux project : http://formilux.ant-computing.com/
 #
 # Copyright (C) 2001-2005 Benoit Dolez & Willy Tarreau
@@ -29,15 +29,26 @@ fi
 # - script name
 
 _cnt2prf="${_mksp_pkg_cnt2prf-${cnt2prf-${SCRIPTDIR:+$SCRIPTDIR/}cnt2prf}}"
-_fix_prf="${_mksp_pkg_fix_prf-${fix_prf-${SCRIPTDIR:+$SCRIPTDIR/}fix-prf"
+_fix_prf="${_mksp_pkg_fix_prf-${fix_prf-${SCRIPTDIR:+$SCRIPTDIR/}fix-prf}}"
 _updt_prf="${_mksp_pkg_updt_prf-${updt_prf-${SCRIPTDIR:+$SCRIPTDIR/}updt-prf}}"
 
+#_="${_mksp_pkg_-${-}}"
+_cp="${_mksp_pkg_cp-${cp-cp}}"
+_ln="${_mksp_pkg_ln-${ln-ln}}"
+_mv="${_mksp_pkg_mv-${mv-mv}}"
+_rm="${_mksp_pkg_rm-${rm-rm}}"
+_find="${_mksp_pkg_find-${find-find}}"
+_mkdir="${_mksp_pkg_mkdir-${mkdir-mkdir}}"
+_sort="${_mksp_pkg_sort-${sort-sort}}"
+_rmdir="${_mksp_pkg_rmdir-${rmdir-rmdir}}"
+_chmod="${_mksp_pkg_chmod-${chmod-chmod}}"
+_chown="${_mksp_pkg_chown-${chown-chown}}"
 
 CMDLINE="$*"
 
 # usage: displays script usage and returns no error.
 function usage {
-  echo "MKSP-PKG - make a pkg dir from several softwares - version 0.0.2 - 2005-09-26"
+  echo "MKSP-PKG - make a pkg dir from several softwares - version 0.0.5 - 2006-01-27"
   echo "Usage: ${myname##*/} { -c |  [ -i <base_dir> ]* [ -prf <base_dir:match> ]* "
   echo "       [ -pkgi <base_dir:file> ]* [ -pkge <base_dir:file> ]* }"
   echo "       -o <out_dir> [ -b build_ver] [ -d ]"
@@ -65,7 +76,7 @@ function die {
 }
 
 function do_clean {
-  rm -rf $OUT_DIR/{fs,base,temp} \
+  $_rm -rf $OUT_DIR/{fs,base,temp} \
   || die "There was an error cleaning the '$OUT_DIR' directory. Aborting."
 }
 
@@ -146,7 +157,7 @@ if [ $PRINTUSAGE -gt 0 -o -z "$OUT_DIR" -o "$OUT_DIR" = "/" -o $CLEAN_ONLY = 0 -
   exit 1
 fi
 
-mkdir -p "$OUT_DIR" || die "Cannot make directory '$OUT_DIR'. Aborting."
+$_mkdir -p "$OUT_DIR" || die "Cannot make directory '$OUT_DIR'. Aborting."
 
 [ -n "${OUT_DIR##/*}" ] && OUT_DIR="$PWD/$OUT_DIR"
 OUT_DIR="${OUT_DIR//\/.\//\/}"
@@ -161,12 +172,12 @@ if [ $CLEAN_ONLY -gt 0 ]; then
   exit 0
 fi
 
-mkdir -p $OUT_DIR/fs || die "Cannot make directory '$OUT_DIR/fs'. Aborting."
-mkdir -p $OUT_DIR/temp || die "Cannot make directory '$OUT_DIR/temp'. Aborting."
+$_mkdir -p $OUT_DIR/fs || die "Cannot make directory '$OUT_DIR/fs'. Aborting."
+$_mkdir -p $OUT_DIR/temp || die "Cannot make directory '$OUT_DIR/temp'. Aborting."
 
 #===================================================================================
 
-mkdir -p $OUT_DIR/temp/{cnt,pkg,prf,cnt-ok,prf-ok} || \
+$_mkdir -p $OUT_DIR/temp/{cnt,pkg,prf,cnt-ok,prf-ok} || \
   die "Cannot make directory '$OUT_DIR/temp/{cnt,pkg,prf,cnt-ok,prf-ok}'. Aborting."
 
 # will contain the total list of prfs, tgz, etc... to be installed
@@ -244,11 +255,11 @@ for IN_DIR in "${IN_DIRS[@]}"; do
   if [ -z "$INCLUDE_FILE" ]; then
     # install everything from this directory (default)
     echo;echo "   +++ Copying all the packages to the medium's data directory +++";echo
-    list=( $(find $IN_DIR/pkg/ -follow -maxdepth 3 -type f -and \( -name \*.tgz -o -name \*.lst -o -name \*.dep \) \
+    list=( $($_find $IN_DIR/pkg/ -follow -maxdepth 3 -type f -and \( -name \*.tgz -o -name \*.lst -o -name \*.dep \) \
 	"${exclude_args[@]}" 2>/dev/null ) )
     if [ ${#list[@]} -gt 0 ]; then
       # FIXME: we should first remove those files if they exist
-      ln -v "${list[@]}" $OUT_DIR/temp/pkg/ 2>/dev/null || cp -avH "${list[@]}" $OUT_DIR/temp/pkg/
+      $_ln -v "${list[@]}" $OUT_DIR/temp/pkg/ 2>/dev/null || $_cp -avH "${list[@]}" $OUT_DIR/temp/pkg/
     else
       echo "   -> No package found in directory $IN_DIR/pkg"
     fi
@@ -256,17 +267,17 @@ for IN_DIR in "${IN_DIRS[@]}"; do
     echo;echo "   +++ Copying all the packages in ${INCLUDE_FILE##*/} to the medium's data directory +++";echo
     while read -r pkg_name; do
 	[ -n "${pkg_name##\#*}" ] || continue
-	list=( $(find $IN_DIR/pkg/ -follow -maxdepth 3 -type f \( -name "$pkg_name" -o -name "$pkg_name[-.]*" \) \
+	list=( $($_find $IN_DIR/pkg/ -follow -maxdepth 3 -type f \( -name "$pkg_name" -o -name "$pkg_name[-.]*" \) \
 		-and \( -name \*.tgz -o -name \*.lst -o -name \*.dep \) \
 		"${exclude_args[@]}" 2>/dev/null ) )
 	if [ ${#list[@]} -gt 0 ]; then
 	  # FIXME: we should first remove those files if they exist
-	  ln -v "${list[@]}" $OUT_DIR/temp/pkg/ 2>/dev/null || cp -avH "${list[@]}" $OUT_DIR/temp/pkg/
+	  $_ln -v "${list[@]}" $OUT_DIR/temp/pkg/ 2>/dev/null || $_cp -avH "${list[@]}" $OUT_DIR/temp/pkg/
 	else
 	  # We did not find this package in the original software dir. Maybe it
 	  # was provided by former software, and is already lying in the dir.
 
-	  nf=( $(find $OUT_DIR/temp/pkg -maxdepth 1 \( -name "$pkg_name" -o -name "$pkg_name[-.]*" \) 2>/dev/null) )
+	  nf=( $($_find $OUT_DIR/temp/pkg -maxdepth 1 \( -name "$pkg_name" -o -name "$pkg_name[-.]*" \) 2>/dev/null) )
 	  if [ ${#nf[@]} -eq 0 ]; then
 	    echo "   -> Not found : $pkg_name"
 	    not_found=( "${not_found[@]}" "$pkg_name" )
@@ -286,20 +297,20 @@ for IN_DIR in "${IN_DIRS[@]}"; do
 
   # 1) we must copy all .prf files we know about
   if [ -e "$IN_DIR/prf" ]; then
-    list=( $(find "$IN_DIR/prf/" -follow -maxdepth 3 -type f "${prflist_args[@]}" -name "*.prf" 2>/dev/null ) )
+    list=( $($_find "$IN_DIR/prf/" -follow -maxdepth 3 -type f "${prflist_args[@]}" -name "*.prf" 2>/dev/null ) )
     FULL_LIST=( "${FULL_LIST[@]}" "${list[@]##*/}" )
-    [ ${#list[@]} -gt 0 ] && cp -avH "${list[@]}" "$OUT_DIR/temp/prf/"
+    [ ${#list[@]} -gt 0 ] && $_cp -avH "${list[@]}" "$OUT_DIR/temp/prf/"
 
     # everything not a .prf can be copied as-is into the target directory
-    list=( $(find "$IN_DIR/prf/" -follow -maxdepth 3 -type f "${prflist_args[@]}" -not -name "*.prf" 2>/dev/null ) )
+    list=( $($_find "$IN_DIR/prf/" -follow -maxdepth 3 -type f "${prflist_args[@]}" -not -name "*.prf" 2>/dev/null ) )
     FULL_LIST=( "${FULL_LIST[@]}" "${list[@]##*/}" )
-    [ ${#list[@]} -gt 0 ] && cp -avH "${list[@]}" "$OUT_DIR/temp/pkg/"
+    [ ${#list[@]} -gt 0 ] && $_cp -avH "${list[@]}" "$OUT_DIR/temp/pkg/"
   fi
 
   # 2) then we must copy all .cnt files
   if [ -e "$IN_DIR/cnt" ]; then
-    list=( $(find "$IN_DIR/cnt/" -follow -maxdepth 3 -type f "${prflist_args[@]}" -name "*.cnt" 2>/dev/null ) )
-    [ ${#list[@]} -gt 0 ] && cp -avH "${list[@]}" "$OUT_DIR/temp/cnt/"
+    list=( $($_find "$IN_DIR/cnt/" -follow -maxdepth 3 -type f "${prflist_args[@]}" -name "*.cnt" 2>/dev/null ) )
+    [ ${#list[@]} -gt 0 ] && $_cp -avH "${list[@]}" "$OUT_DIR/temp/cnt/"
   fi
 
   # 3) Now, let's fix the .prf. It's important to do this before merging other packages
@@ -313,17 +324,19 @@ for IN_DIR in "${IN_DIRS[@]}"; do
     echo "If you need to fix files, those were initially found here : $IN_DIR/prf"
     exit 1
   else
-    rmdir $OUT_DIR/temp/prf/rescan $OUT_DIR/temp/prf/rescan.log 2>/dev/null
+    $_rmdir $OUT_DIR/temp/prf/rescan $OUT_DIR/temp/prf/rescan.log 2>/dev/null
   fi
   # move the prfs to their destination now, so that we don't risk rescanning them
-  [ -n "$(echo $OUT_DIR/temp/prf/*)" ] && mv $OUT_DIR/temp/prf/* $OUT_DIR/temp/prf-ok/
+  [ -n "$(echo $OUT_DIR/temp/prf/*)" ] && $_mv $OUT_DIR/temp/prf/* $OUT_DIR/temp/prf-ok/
   # the prf dir is now empty and available for next round
 
   # 4) we generate the .prf from .cnt, possibly overwriting the ones copied in (1 and 3)
   if [ -n "$(echo $OUT_DIR/temp/cnt/*)" ]; then
     for cnt in "$OUT_DIR"/temp/cnt/*.cnt; do
       prf="${cnt%.cnt}.prf"
-      $_cnt2prf < "$cnt" | PKGDIRS="$OUT_DIR/temp/pkg" $_fix_prf > "$prf"
+      # we'll convert the cnt files to prf while ensuring that their version is
+      # respected.
+      $_cnt2prf < "$cnt" | PKGDIRS="$OUT_DIR/temp/pkg" $_fix_prf -s2 > "$prf"
       FULL_LIST=( "${FULL_LIST[@]}" "${prf##*/}" )
     done
 
@@ -337,26 +350,26 @@ for IN_DIR in "${IN_DIRS[@]}"; do
       echo "If you need to fix files, those were initially found here : $IN_DIR/cnt"
       exit 1
     else
-      rmdir $OUT_DIR/temp/cnt/rescan $OUT_DIR/temp/cnt/rescan.log 2>/dev/null
+      $_rmdir $OUT_DIR/temp/cnt/rescan $OUT_DIR/temp/cnt/rescan.log 2>/dev/null
     fi
-    [ -n "$(echo $OUT_DIR/temp/cnt/*.prf)" ] && mv $OUT_DIR/temp/cnt/*.prf $OUT_DIR/temp/prf-ok/ 2>/dev/null
-    [ -n "$(echo $OUT_DIR/temp/cnt/*.cnt)" ] && mv $OUT_DIR/temp/cnt/* $OUT_DIR/temp/cnt-ok/ 2>/dev/null
+    [ -n "$(echo $OUT_DIR/temp/cnt/*.prf)" ] && $_mv $OUT_DIR/temp/cnt/*.prf $OUT_DIR/temp/prf-ok/ 2>/dev/null
+    [ -n "$(echo $OUT_DIR/temp/cnt/*.cnt)" ] && $_mv $OUT_DIR/temp/cnt/* $OUT_DIR/temp/cnt-ok/ 2>/dev/null
     # the cnt dir is now empty and available for next round
   fi
 done
 
-chown -R root:root $OUT_DIR/temp/pkg 2>/dev/null
-chmod -R ugo+rX $OUT_DIR/temp/pkg 2>/dev/null
+$_chown -R root:root $OUT_DIR/temp/pkg 2>/dev/null
+$_chmod -R ugo+rX $OUT_DIR/temp/pkg 2>/dev/null
 
-#mv $OUT_DIR/temp/cnt-ok/* $OUT_DIR/fs/
-[ -n "$(echo $OUT_DIR/temp/pkg/*)" ] && cp -aH $OUT_DIR/temp/pkg/* $OUT_DIR/fs/
-[ -n "$(echo $OUT_DIR/temp/prf-ok/*)" ] && cp -aH $OUT_DIR/temp/prf-ok/* $OUT_DIR/fs/
+#$_mv $OUT_DIR/temp/cnt-ok/* $OUT_DIR/fs/
+[ -n "$(echo $OUT_DIR/temp/pkg/*)" ] && $_cp -aH $OUT_DIR/temp/pkg/* $OUT_DIR/fs/
+[ -n "$(echo $OUT_DIR/temp/prf-ok/*)" ] && $_cp -aH $OUT_DIR/temp/prf-ok/* $OUT_DIR/fs/
 
 # put the full list of packages to be installed in the target dir
 # FIXME: there can be duplicates from conflicting prf & cnt.
-for prf in "${FULL_LIST[@]}"; do echo "$prf"; done | sort -u > $OUT_DIR/fs/.FULL_LIST
+for prf in "${FULL_LIST[@]}"; do echo "$prf"; done | $_sort -u > $OUT_DIR/fs/.FULL_LIST
 
-[ $DEBUG -eq 0 ] && rm -rf $OUT_DIR/temp
+[ $DEBUG -eq 0 ] && $_rm -rf $OUT_DIR/temp
 
 echo
 echo "+++ Done ! +++";
diff --git a/build/mksp-raw b/build/mksp-raw
--- a/build/mksp-raw
+++ b/build/mksp-raw
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# mksp-raw - make a root fs from packages - version 0.0.3 - 2005-10-16
+# mksp-raw - make a root fs from packages - version 0.0.4 - 2006-01-27
 # This file is part of the Formilux project : http://formilux.ant-computing.com/
 #
 # Copyright (C) 2001-2003 Benoit Dolez & Willy Tarreau
@@ -9,11 +9,32 @@
 #
 # This program is licenced under GPLv2 ( http://www.gnu.org/licenses/gpl.txt )
 
+#### update PATH to include this script's directory
+MYDIR="${0%/*}"
+[ "${PATH#$MYDIR:}" == "$PATH" ] && export PATH="$MYDIR:$PATH"
+
+#### source defaults file if it exists
+FLXDEFAULTS="${FLXDEFAULTS-$HOME/.flxdefaults}"
+if [ -r "$FLXDEFAULTS" ]; then
+  . "$FLXDEFAULTS"
+fi
+
+# Searches for scripts in this order :
+# - _mksp_raw_<script name>
+# - <script name>
+# - $SCRIPTDIR/<script name>
+# - script name
+
+_flxextract="${_mksp_raw_flxextract-${flxextract-${SCRIPTDIR:+$SCRIPTDIR/}flxextract}}"
+_ln="${_mksp_raw_ln-${ln-ln}}"
+_mkdir="${_mksp_raw_mkdir-${mkdir-mkdir}}"
+_tar="${_mksp_raw_tar-${tar-tar}}"
+
 CMDLINE="$*"
 
 # usage: displays script usage and returns no error.
 function usage {
-  echo "MKSP-RAW - make a root fs from packages - version 0.0.2 - 2005-09-26"
+  echo "MKSP-RAW - make a root fs from packages - version 0.0.4 - 2006-01-27"
   echo "Usage: ${myname##*/} { -c |  [ -pkg <pkg_dir> ]* -prf <prf_dir>"
   echo "       -o <out_dir> [ -d ]"
   echo
@@ -46,8 +67,6 @@ myname="$0"
 PRINTUSAGE=0
 CLEAN_ONLY=0
 DEBUG=0
-
-_FLXEXTRACT="${SCRIPTDIR:+$SCRIPTDIR/}flxextract"
 
 unset PKG_ARG OUT_DIR PRF
 
@@ -98,7 +117,7 @@ if [ $PRINTUSAGE -gt 0 -o -z "$OUT_DIR" -o "$OUT_DIR" = "/" -o $CLEAN_ONLY = 0 -
   exit 1
 fi
 
-mkdir -p "$OUT_DIR" || die "Cannot make directory '$OUT_DIR'. Aborting."
+$_mkdir -p "$OUT_DIR" || die "Cannot make directory '$OUT_DIR'. Aborting."
 
 [ -n "${OUT_DIR##/*}" ] && OUT_DIR="$PWD/$OUT_DIR"
 OUT_DIR="${OUT_DIR//\/.\//\/}"
@@ -113,9 +132,9 @@ if [ $CLEAN_ONLY -gt 0 ]; then
   exit 0
 fi
 
-mkdir -p $OUT_DIR/fs || die "Cannot make directory '$OUT_DIR/fs'. Aborting."
-mkdir -p $OUT_DIR/log || die "Cannot make directory '$OUT_DIR/log'. Aborting."
-ln -s $PRF $OUT_DIR/base || die "Cannot make link '$OUT_DIR/base'. Aborting."
+$_mkdir -p $OUT_DIR/fs || die "Cannot make directory '$OUT_DIR/fs'. Aborting."
+$_mkdir -p $OUT_DIR/log || die "Cannot make directory '$OUT_DIR/log'. Aborting."
+$_ln -s $PRF $OUT_DIR/base || die "Cannot make link '$OUT_DIR/base'. Aborting."
 
 #===================================================================================
 
@@ -124,10 +143,10 @@ echo;echo "+++ rebuilding the root FS +++";echo
 for i in "$PRF"/[0-9]*.{prf,tgz}; do
     echo "Extracting $i..."
     case "$i" in
-	*.prf) $_FLXEXTRACT -i "$i" -l $OUT_DIR/log/${i##*/}.log "${PKG_ARG[@]}" -R $OUT_DIR/fs \
+	*.prf) $_flxextract -i "$i" -l $OUT_DIR/log/${i##*/}.log "${PKG_ARG[@]}" -R $OUT_DIR/fs \
                || die "There was an error while extracting some files. Aborting."
 	       ;;
-	*.tgz) tar -C $OUT_DIR/fs -zUpxf $i \
+	*.tgz) $_tar -C $OUT_DIR/fs -zUpxf $i \
 	       || die "There was an error while extracting some files. Aborting."
 	       ;;
     esac
