scripts: restore support for globbing in flxrescan/flxextract
While originally it was possible to extract all files from a specific
package, this got lost when better checks were added. It was discussed
lately about reintroducing this. This requires to be able to process
multiple entries for a single one. This is what this patch does. Its
only limitation is that at least one file must match, so it's not
possible to opportunistically use "/path/to/*" and support empty dirs.
Also, "**" is supported to match across directories so it can be an
option to support optionally empty directories, e.g. if a component
needs to match dirs and files.

diff --git a/scripts/flxextract b/scripts/flxextract
--- a/scripts/flxextract
+++ b/scripts/flxextract
@@ -1,9 +1,9 @@
 #!/bin/bash
 #
-# flxextract - package extracter - version 0.0.4 - 2006-07-17
+# flxextract - package extracter - version 0.0.5 - 2025-09-03
 # This file is part of the Formilux project : http://formilux.ant-computing.com/
 #
-# Copyright (C) 2001-2003 Benoit Dolez & Willy Tarreau
+# Copyright (C) 2001-2025 Benoit Dolez & Willy Tarreau
 #       mailto: benoit@ant-computing.com,willy@ant-computing.com
 #
 # This program is licenced under GPLv2 ( http://www.gnu.org/licenses/gpl.txt )
@@ -32,24 +32,37 @@ function main {
 	    continue
         fi
 
-	set -- $(awk "/${file##*/}/ { if (\$8==\"$file\") print \$0; }" $pkgsrc)
-	if [ -z "$*" ]; then
-	    echo -n "F" >&2
-	    echo "##not found## $file $pkgsrc" >> $LOGFILE
-            continue
-        fi
-        if [ "x$1" = "xd" ]; then
-	    # it's a directory
-            rm -f $ROOTDIR/$8 >/dev/null 2>&1 # just in case it was something else
-	    mkdir -p $ROOTDIR/$8
-	    touch -t $(date -d "Jan 1 00:00:00 UTC 1970 + $7 sec" +"%Y%m%d%H%M.%S" ) $ROOTDIR/$8
-   	    chown $3:$4 $ROOTDIR/$8
-   	    chmod $2 $ROOTDIR/$8
-	    echo "$8/" >> $LOGFILE
-        else
-	    # it's a regular file
-	    echo $8 $pkgsrc >> $SFILES
-        fi
+        # support extracting files designated by '*'/'?'/'**' in prf
+        awk "{re = \"$file\";
+              gsub(/([.()|+^\$\\\\])/, \"\\\\\\\\&\", re); # Escape regex chars
+              gsub(/\*/, \"[^/]*\", re); # *: any string except '/'
+              gsub(/\[\^\/\]\*\[\^\/\]\*/, \".*\", re);  # **: any string including '/'
+              gsub(/\?/, \"[^/]\", re);  # ?: any char but '/'
+              gsub(/\[!/, \"[^\", re);   # [!abc] becomes [^abc]
+              re = \"^\" re \"\$\";      # full match
+              if (\$8 ~ re) print \$0; }" "$pkgsrc" | \
+        (
+            cnt=0
+            while read type mode user grp size sig date name other; do
+                if [ "$type" = "d" ]; then
+	            # it's a directory
+                    rm -f "$ROOTDIR"/"$name" >/dev/null 2>&1 # just in case it was something else
+	            mkdir -p "$ROOTDIR"/"$name"
+	            touch -t $(date -d "Jan 1 00:00:00 UTC 1970 + $date sec" +"%Y%m%d%H%M.%S" ) "$ROOTDIR"/"$name"
+                    chown $user:$grp "$ROOTDIR"/"$name"
+                    chmod $mode "$ROOTDIR"/"$name"
+	            echo "$name/" >> "$LOGFILE"
+                else
+	            # it's a regular file
+	            echo "$name" "$pkgsrc" >> "$SFILES"
+                fi
+                ((cnt++))
+            done
+            if [ $cnt -eq 0 ]; then
+                echo -n "F" >&2
+                echo "##not found## $file $pkgsrc" >> $LOGFILE
+            fi
+        )
     done < $LFILES
 
     echo >&2 ; echo -n "Extracting files ..." >&2
