scripts/pkg: add "pkg prefetch" to prefetch a package's source
This can be used to check availability and/or to preload into the cache.
Cacheable methods will be available for later. A good way to use it is
by doing this to prefetch all sources before starting to build:

   pkg-filter list | xargs -n 1 pkg prefetch

Or even better, with error reporting:

  pkg-filter list | grep -v -- -0local- | while read; do
    pkg prefetch $REPLY || { echo "## Failed to prefetch '$REPLY'."; break; }
  done

Note that the downloads must not be run concurrently because the ".src"
file is still being used from the current directory to store the temporary
download.

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -2305,7 +2305,9 @@ function get_svncached_file {
 # get package. Note that we have to try two decompression methods because some
 # recent versions of "tar" are not able to correctly detect the XZ format.
 # $1=path, $2=method, $3=extract, others ignored.
-# Extraction method "tar" (default) causes archive to be extracted.
+# Extraction method "tar" (default) causes archive to be extracted; "copy" to
+# copy it as-is; "prefetch" to remove it after download (hence it only
+# prefetches into the cache for cachable ones).
 function get_package {
   case "$2" in
 	svn)
@@ -2316,11 +2318,16 @@ function get_package {
 	        (echo "Retrying using XZ format"; tar --exclude="$PKGLINK" --strip-components=${TAR_STRIP_COMP:-1} ${VERBOSE} -Jxf .src) || return 1
 	    elif [ "$3" = "copy" ]; then
 	      cp .src "${1##*/}"
+            elif [ "$3" = "prefetch" ]; then
+              rm -f .src
 	    fi
 	  )
  	;;
 	git)
-	  git clone "$1" src
+	  git clone "$1" src || return 1
+          if [ "$3" = "prefetch" ]; then
+              rm -rf .src
+          fi
 	;;
 	http|ftp)
 	  (
@@ -2330,6 +2337,8 @@ function get_package {
 	        (echo "Retrying using XZ format"; tar --exclude="$PKGLINK" --strip-components=${TAR_STRIP_COMP:-1} ${VERBOSE} -Jxf .src) || return 1
 	    elif [ "$3" = "copy" ]; then
 	      cp .src "${1##*/}"
+            elif [ "$3" = "prefetch" ]; then
+              rm -f .src
 	    fi
 	  )
 	;;
@@ -2343,6 +2352,8 @@ function get_package {
 	    fi
 	  elif [ "$3" = "copy" ]; then
 	    cp .src "${1##*/}"
+          elif [ "$3" = "prefetch" ]; then
+            rm -f .src
 	  fi
 	;;
 	*)
@@ -2351,7 +2362,7 @@ function get_package {
 	;;
   esac
   RET=$?
-  if [ "$RET" == "0" ]; then
+  if [ "$RET" == "0" -a "$3" != "prefetch" ]; then
     touch .unpacked
   fi
   return $RET
@@ -2382,6 +2393,35 @@ function do_source {
     fi
     rm -f .patched  # we must re-apply patches
     return 0  
+  fi
+}
+
+# download the source package through the cache and drop it. This can be
+# used to refresh the cache and/or check availability of the package. Some
+# methods are not stored into the cache (git, FS) and will just be copied
+# then dropped.
+function do_prefetch {
+  echo "Re-using package ${REPLY}"
+  echo "Downloading source package ${REPLY}..."
+  if [ -z "$SRC_FETCH_PATH" -a -z "$SRC_FETCH_METHOD" ]; then
+    echo "No source package nor source fetch method. assume package does not need sources"
+    return 0
+  fi
+  if [ -z "$SRC_FETCH_PATH" ]; then
+    echo "No source package specified SRC_FETCH_PATH"
+    return 2
+  fi
+  if [ -z "$SRC_FETCH_METHOD" ]; then
+    echo "No SRC_FETCH_METHOD"
+    return 1
+  fi
+  if [ -n "$SRC_FETCH_PATH" ]; then
+    get_package "$SRC_FETCH_PATH" "$SRC_FETCH_METHOD" "prefetch" "$1"
+    if [ "$?" != "0" ]; then
+      echo "Error on downloading."
+      return 1
+    fi
+    return 0
   fi
 }
 
@@ -2879,7 +2919,7 @@ function usage {
     echo "  pkg setpkg [ new_pkg ]"
     echo "    ex: pkg setpkg openssl-0.9.6g-${BUILDSFX}${BUILDVER}.1"
     echo
-    echo "  pkg { info|cat|edit|unpack|changelog|tar|home|log|check } [ pkg ]"
+    echo "  pkg { info|cat|edit|unpack|changelog|tar|home|log|check|prefetch } [ pkg ]"
     echo "    ex: pkg info"
     echo "        pkg info bash"
     echo "        pkg edit modutils-2.4"
@@ -3413,7 +3453,7 @@ while [ $CHAINCMD -gt 0 -a ${#ARGLIST[@]} -gt 0 ]; do
 	    KNOWNCMD=1
 	    pkgfilefind $1
 	    ;;
-	info|edit|cat|unpack|changelog|tar|home|log|check)
+	info|edit|cat|unpack|changelog|tar|home|log|check|prefetch)
 	    CHAINCMD=0
 	    KNOWNCMD=1
 	    get_name ${ARGLIST[0]} %L %P %D
