scripts: pkg: support schemed repo path
pkg and pkg-cache now support defining a repo by its ssh or file url such as:
	ssh://<server>/<path>
	file://<path>

Note that these formats still work:
	<path>
	<sshserver>:<path>

Status code 3 is used in case the URL cannot be parsed. Note that
the file:// representation requires a path starting with a '/', hence
results in 3 consecutive '/' (like in browsers).

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -2936,17 +2936,24 @@ function do_changelog {
 # run <cmd> on a [remote] path
 # in:   cmd, the command to run
 #       [options ...], <cmd> options
-#       path ( /etc/foobar or server:/etc/foobar )
-# return: return from <cmd> or ssh error code
+#       path (ie /etc/foobar or <server>:/etc/foobar or ssh://<server>/etc/foobar )
+# return: return from <cmd> or ssh error code or 3 in case of parsing error for <path>.
 #
-# if path is in the form <server>:<path>, then ssh <server> <cmd> <options> <path> is evalated
-# otherwise evaluates <cmd> <options> <path>
+# if path is in the form ssh://<hostname>/<path>
+# or path is in the form <hostname>:<path> then run
+#	ssh <hostname> <cmd> <options> <path>
+# else if path is in the form file:///<path> then run
+#	<cmd> <options> <path>
+# else if path is anything else with ':' before '/', or with any other scheme,
+# then fail with error 3.
+# otherwise run
+#	<cmd> <options> <path>
 #
 # This function works for tools like touch or chmod - but taking a single path
 # The expected pattern to call the tool is:
 #  <tool> <options> <path> (WARNING single path parameter only)
 function rcmd() {
-    [ $# -ne 0 ] || return 255
+    [ $# -ne 0 ] || return 3
 
     local cmd="$1";  shift
     if [ $# -eq 0 ]; then
@@ -2956,12 +2963,29 @@ function rcmd() {
 
     # last param -> the path to run "cmd" against (WARNING - only one supported)
     local path="${!#}"
-    if [[ ${path} =~ ^[^/]*:.* ]]; then
-        local -a cmd_params
-        for ((i=1; i<=$#-1; i++)); do
-            cmd_params[i]="\"${!i}\""
-        done
-        ssh "${path%%:*}" "${cmd}" "${cmd_params[@]}" "\"${path#*:}\""
+
+    if [[ ${path} =~ (^[^/]*)://([^/]*)(/.*) ]] || [[ ${path} =~ (^)([^/]*):(.*) ]] ; then
+        local scheme="${BASH_REMATCH[1]}"
+        local hostname="${BASH_REMATCH[2]}"
+        local rpath="${BASH_REMATCH[3]}"
+
+        case "$scheme" in
+            ""|"ssh")
+                [[ ! -z "${hostname}" ]] || return 3
+                local -a cmd_params
+                for ((i=1; i<=$#-1; i++)); do
+                    cmd_params[i]="\"${!i}\""
+                done
+                ssh "${hostname}" "${cmd}" "${cmd_params[@]}" "\"${rpath}\""
+            ;;
+            "file")
+                [[ -z "${hostname}" ]] || return 3
+                "${cmd}" "${@:1:$(($#-1))}" "${rpath}"
+            ;;
+            *)
+                return 3
+            ;;
+        esac
     else
         "${cmd}" "$@"
     fi
