scripts: pkg: add the "log" command
Till now the only way to consult log has always been to run "changelog"
then to quit the editor. This command is used quite a bit so let's just
implement "pkg log" which can either show a specific package's log or
the current one's.

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -2871,7 +2871,7 @@ function usage {
     echo "  pkg setpkg [ new_pkg ]"
     echo "    ex: pkg setpkg openssl-0.9.6g-${BUILDSFX}${BUILDVER}.1"
     echo
-    echo "  pkg { info|cat|edit|unpack|changelog|tar|home } [ pkg ]"
+    echo "  pkg { info|cat|edit|unpack|changelog|tar|home|log } [ pkg ]"
     echo "    ex: pkg info"
     echo "        pkg info bash"
     echo "        pkg edit modutils-2.4"
@@ -3161,6 +3161,34 @@ function do_home {
     return 0
 }
 
+# shows the packages's changelog in a pager.
+function do_log {
+    local cmd
+
+    # some important checks before things get wrong
+    if [ -z "$PKGDIR" -o -z "$EXACTPKG" ]; then
+	echo "Critical error : PKGDIR and EXACTPKG must be set !"
+	exit 1
+    fi
+
+    # some important checks before things get wrong
+    if [ ! -e "$PKGDIR/ChangeLog" ]; then
+	echo "Critical error : no ChangeLog file in $PKGDIR!"
+	exit 1
+    fi
+
+    if [ -n "$PAGER" ]; then
+        cmd="$PAGER"
+    elif [ -n "$LESS" -o -n "LESSOPEN" ]; then
+        cmd="less"
+    else
+        cmd="more"
+    fi
+
+    "$cmd" "$PKGDIR/ChangeLog"
+    return 0
+}
+
 # emits a tar of the minimal package
 function do_tar {
     local last_pkg
@@ -3323,7 +3351,7 @@ while [ $CHAINCMD -gt 0 -a ${#ARGLIST[@]} -gt 0 ]; do
 	    KNOWNCMD=1
 	    pkgfilefind $1
 	    ;;
-	info|edit|cat|unpack|changelog|tar|home)
+	info|edit|cat|unpack|changelog|tar|home|log)
 	    CHAINCMD=0
 	    KNOWNCMD=1
 	    get_name ${ARGLIST[0]} %L %P %D
