scripts/pkg: make pkg diff automatically use the last release package
When no argument is passed to "pkg diff", it will now check the changelog
for the last released version and use it as a base for the diff. Practically
speaking this means that issuing "pkg diff" on a package currently being
edited will show the changes since the last release, i.e. the uncommitted
changes.

If it cannot figure the previous version it will just print an error
message inviting the user to pass the package name.

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -2925,7 +2925,7 @@ function usage {
     echo "        pkg edit modutils-2.4"
     echo "        pkg cat gzip-1.3"
     echo ""
-    echo "  pkg { diff } pkg1 [pkg2]"
+    echo "  pkg { diff } [pkg1 [pkg2]]"
     echo
     echo "  pkg { clean | compile | config | compile_only | build }*"
     echo "  pkg { prepack | strip | pack | delpack | release }*"
@@ -3526,17 +3526,9 @@ while [ $CHAINCMD -gt 0 -a ${#ARGLIST[@]} -gt 0 ]; do
     fi
 
     # run a diff between the two packages $1 and $2
+    # if $2 is missing, use the current one.
+    # if $1 is missing, use the last released one from the current one's log
     if [ "$ACTION" == "diff" ]; then
-        if [ -z "$1" ]; then
-            echo "Error: the 'diff' command requires one or two package names."
-            exit 1
-        fi
-
-        if ! h1=$("$_PKG" home "$1"); then
-            echo "Error: failed to retrieve home dir for package '$1'."
-            exit 1
-        fi
-
         if [ -n "$2" ]; then
             if ! h2=$("$_PKG" home "$2"); then
                 echo "Error: failed to retrieve home dir for package '$2'."
@@ -3549,6 +3541,19 @@ while [ $CHAINCMD -gt 0 -a ${#ARGLIST[@]} -gt 0 ]; do
                 exit 1
             fi
             h2="$PKGDIR"
+        fi
+
+        if [ -z "$1" ]; then
+            set -- $(EXACTPKG=1 do_log | sed -ne '/\* released \(.*\)/{s/^\s*\* released \(.*\)/\1/p;q}')
+            if [ -z "$1" ]; then
+                echo "Error: previous package version could not be determined from changelog, please specify it."
+                exit 1
+            fi
+        fi
+
+        if ! h1=$("$_PKG" home "$1"); then
+            echo "Error: failed to retrieve home dir for package '$1'."
+            exit 1
         fi
 
         exec diff -durN --color --no-dereference -F '^\s*function\s\|[0-9a-zA-Z_]()\s*{$' "$h1" "$h2"
