scripts: pkg: automatically call do_check from do_release()
This now allows to run a quick sanity check on the package which is
about to be released. It will warn if some suspicious files were
found or if some unused patches were found, and will ask whether
or not the user wants to continue.

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -3101,6 +3101,20 @@ function do_release {
 	exit 1
     fi
 
+    # perform a few sanitfy checks for unused patches and junk files
+    if [ "$PKG_NOCHOICE" != "1" ] && ! do_check; then
+        echo
+        REPLY=""
+        while [ "$REPLY" != "y" -a "$REPLY" != "n" ] &&
+              read -p "Some sanity checks failed, are you sure you still want to release [y/n]? "; do
+             :
+        done
+        if [ "$REPLY" != "y" ]; then
+            echo "Aborting!"
+            exit 1
+        fi
+    fi
+
     # identify last changelog entry
     last_pkg=""
     if [ -e "$PKGDIR/ChangeLog" ]; then
