* pkg : version 0.9.0
Add support for static- and shared- outputs for use in buildroots.

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# pkg - Formilux package builder - version 0.8.4 - 2007-03-11
+# pkg - Formilux package builder - version 0.9.0 - 2007-11-12
 #
 # Copyright (C) 2001-2005 Benoit Dolez & Willy Tarreau
 #       mailto: benoit@ant-computing.com,willy@ant-computing.com
@@ -8,7 +8,7 @@
 # This program is licenced under GPLv2 ( http://www.gnu.org/licenses/gpl.txt )
 
 ######## Please update this version ########
-PKG_VERSION=0.8.3
+PKG_VERSION=0.9.0
 ############################################
 
 ## WARNING ##
@@ -72,6 +72,18 @@ PATCH_LEVEL=${PATCH_LEVEL:-1}
 # versions with this name followed by a number (BUILDVER)
 BUILDSFX=${BUILDSFX:-flx}
 BUILDVER=${BUILDVER:-0}
+
+# supported build models are "normal", "static", "shared"
+BUILDMODELS=( "${BUILDMODELS[@]}" )
+BUILDMODEL="${BUILDMODEL}"
+FLXPREFIX="/usr"
+
+# set to non-empty if model enabled. Both are set to
+# supported models if BUILDMODELS is set.
+ENABLE_SHARED=
+ENABLE_STATIC=
+DISABLE_SHARED=
+DISABLE_STATIC=
 
 PKGSUFF="tgz"
 CFGSUFF="cfg"
@@ -500,14 +512,101 @@ function set_default_perm {
 ######
 
 # builds everything from a clean start
-function do_build {
+function do_build_normal {
     local ACTION
+    export FLXPREFIX="/usr"
+
+    # set the flags if the package supports the models
+    if [ "${BUILDMODELS[*]##shared}" != "${BUILDMODELS[*]}" ]; then
+        export ENABLE_SHARED=y
+        export DISABLE_SHARED=
+    else
+        export ENABLE_SHARED=
+        export DISABLE_SHARED=y
+    fi
+
+    if [ "${BUILDMODELS[*]##static}" != "${BUILDMODELS[*]}" ]; then
+        export ENABLE_STATIC=y
+        export DISABLE_STATIC=
+    else
+        export ENABLE_STATIC=
+        export DISABLE_STATIC=y
+    fi
+
     # ACTION will be inherited by other functions
     for ACTION in clean compile prepack strip pack ; do
 	declare -f pre_$ACTION > /dev/null && { ( pre_$ACTION $* ) || return $?; }
 	declare -f do_$ACTION > /dev/null && { ( do_$ACTION $* ) || return $?; }
 	declare -f post_$ACTION > /dev/null && { ( post_$ACTION $* ) || return $?; }
     done
+    return 0
+}
+
+function do_build_static {
+    local ACTION
+    export FLXPREFIX=/usr/$PKGRADIX-$PKGVER/static
+    export ENABLE_SHARED=
+    export ENABLE_STATIC=y
+    export DISABLE_SHARED=y
+    export DISABLE_STATIC=
+    # ACTION will be inherited by other functions
+    for ACTION in clean compile prepack strip pack ; do
+	declare -f pre_$ACTION > /dev/null && { ( pre_$ACTION $* ) || return $?; }
+	declare -f do_$ACTION > /dev/null && { ( do_$ACTION $* ) || return $?; }
+	declare -f post_$ACTION > /dev/null && { ( post_$ACTION $* ) || return $?; }
+    done
+    return 0
+}
+
+function do_build_shared {
+    local ACTION
+    export FLXPREFIX=/usr/$PKGRADIX-$PKGVER/shared
+    export ENABLE_SHARED=y
+    export ENABLE_STATIC=
+    export DISABLE_SHARED=
+    export DISABLE_STATIC=y
+    # ACTION will be inherited by other functions
+    for ACTION in clean compile prepack strip pack ; do
+	declare -f pre_$ACTION > /dev/null && { ( pre_$ACTION $* ) || return $?; }
+	declare -f do_$ACTION > /dev/null && { ( do_$ACTION $* ) || return $?; }
+	declare -f post_$ACTION > /dev/null && { ( post_$ACTION $* ) || return $?; }
+    done
+    return 0
+}
+
+function do_build {
+    local model models ret oldmod
+
+    # BUILDMODEL may be forced to build only one model.
+    # Also, if no BUILDMODELS are defined for a package, let's only
+    # build the "normal" one.
+    if [ -n "$BUILDMODEL" ]; then
+	if [ "$BUILDMODEL" != "normal" -a \
+             "${BUILDMODELS[*]##$BUILDMODEL}" == "${BUILDMODELS[*]}" ]; then
+            echo "ERROR: model $BUILDMODEL is not supported by this package (check BUILDMODEL)."
+            return 1
+        fi
+        models=( $BUILDMODEL )
+    else
+        if [ -z "${BUILDMODELS[*]}" ]; then
+	    models=( "normal" )
+	else
+            models=( normal static shared )
+	fi
+    fi
+
+    oldmod="$BUILDMODEL"
+    for model in ${models[*]}; do
+	export BUILDMODEL="$model"
+	echo "Building for model '$BUILDMODEL'."
+	# skip unsupported models, except "normal" which is always supported
+	[ "$model" != "normal" -a \
+	  "${BUILDMODELS[*]##$model}" == "${BUILDMODELS[*]}" ] && \
+	    continue
+	do_build_${model}; ret=$?; [ $ret -eq 0 ] || return $ret
+    done
+    # restore BUILDMODEL
+    export BUILDMODEL="$oldmod"
     return 0
 }
 
@@ -1162,6 +1261,16 @@ function _do_pack_files {
     FPNAME=$PKGDIR/compiled/${EXACTPKG##*/}-$FLXARCH
     DEP_FILE=$FPNAME.dep
 
+    # If we're currently building a "build" model, we just want the tgz with
+    # its specific extension.
+    if [ "$BUILDMODEL" == "shared" -o "$BUILDMODEL" == "static" ]; then
+        echo -n "Creating $FPNAME.$BUILDMODEL ... "
+        # we want everything, including directories.
+        cut -f1 -d' ' $FILE_LIST|sed -e 's,/$,,' | tar -T - --no-recursion --numeric-owner -cf - | gzip -9 >$FPNAME.$BUILDMODEL 2>/dev/null
+	echo "done."
+	return 0
+    fi
+
     rm -rf $DEP_FILE
     if [ -e $DEP_FILE.diff ] ; then cat $DEP_FILE.diff > $DEP_FILE ; fi
 
@@ -1298,6 +1407,18 @@ function do_pack {
     # full path name of different files
     FPNAME=$PKGDIR/compiled/${EXACTPKG##*/}-$FLXARCH
     DEP_FILE=$FPNAME.dep
+
+    # If we're currently building a "build" model, we just want the tgz with
+    # its specific extension.
+    if [ "$BUILDMODEL" == "shared" -o "$BUILDMODEL" == "static" ]; then
+        echo -n "Creating $FPNAME.$BUILDMODEL ... "
+        # we want everything, and directories only if they're empty. 
+        # All this without './' we shouldn't get an empty line since . 
+        # should contain at least what we want to tar !
+        $FIND_CMD . | tar --no-recursion -T - --numeric-owner -cf - | gzip -9 >$FPNAME.$BUILDMODEL 2>/dev/null
+	echo "done."
+	return 0
+    fi
 
     # rebuild dependencies file, first is a diff file
     echo -n "Creating $DEP_FILE ... "
@@ -1626,7 +1747,7 @@ function print_env {
 	    GCC_OPT_FASTEST GCC_OPT_FAST GCC_OPT_SMALL \
 	    HOSTCC HOSTCXX \
 	    HOSTCC_OPT_FASTEST HOSTCC_OPT_FAST HOSTCC_OPT_SMALL \
-	    FLXMAKE FLXPMAKE; do
+	    FLXMAKE FLXPMAKE BUILDMODEL FLXPREFIX; do
      echo "$i=$(eval echo \$$i)"
    done
    exit 0
