pkg: svn rev r15275: check that the sysroot tar file exists before cleaning sysroot
It saves us from deleting an old-style sysroot for which we have no backup.

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -1775,6 +1775,12 @@ function do_pack {
 
 # this function extract the sys-root and dependencies into it
 function do_prepare {
+  if [ -z "${SYSROOTTAR}" -o ! -e "${SYSROOTTAR}" ]; then
+	echo "Error: sysroot tar file not found (\$SYSROOTTAR = \"$SYSROOTTAR\")."
+	echo "Refusing to remove sysroot."
+	exit 1
+  fi
+
   if [ -z "$DONTCLEANSYSROOT" ]; then
         echo "* Cleaning sysroot"
 	rm -rf "${FLXROOTDIR}"
