pkg: svn rev r13272: New version of pkg
WT: post analysis of this patch :
  - this version imports the generic install-* functions, and does
    various unknown things on the dependencies and get_package.

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -46,6 +46,7 @@ PKG_VERSION=0.10.0
 #   pkg { any_command } [ any_args ]
 #
 
+
 # don't return stupid names, and we also want dotfiles and use extended globbing
 shopt -s nullglob
 shopt -s dotglob
@@ -374,10 +375,86 @@ function sortnames {
     echo "${list[*]}" | sort -t , $flist | cut -f2 -d~
 }
 
-
 ######
 ###### here are some "exported" functions used to ease file manipulation
 ######
+
+# usage: install-files <owner> <perm> <dest> file...
+#
+function install-files {
+  local owner="$1" ; shift
+  local perm="$1" ; shift
+  local dst="$1" ; shift
+  local file
+
+  [ -n "${dst##*/*}" -o -d "$ROOTDIR/${dst%/*}" ] \
+        || mkdir -p "$ROOTDIR/${dst%/*}"
+
+  cp -dpfPL "$@" "$ROOTDIR/$dst/" && \
+    ( cd "$ROOTDIR/$dst" && chown -h $owner "${@##*/}" \
+        && chmod $perm "${@##*/}" )
+
+  [ -n "$FILE_LIST" ] \
+        && for file in "$@"; do
+        echo "$dst/$file"
+  done  >> $FILE_LIST
+}
+
+# usage: install-file <owner> <perm> <file> <dest>
+#
+function install-file {
+  local owner="$1" ; shift
+  local perm="$1" ; shift
+  local src="$1" ; shift
+  local dst="$1" ; shift
+
+  if [ -e "$src.$MODEL" ] ; then
+	src="$src.$MODEL"
+  fi
+
+  # replace %% by $dst in src
+  src=${src//\%\%/$dst}
+ 
+  [ -n "${dst##*/*}" -o -d "$ROOTDIR/${dst%/*}" ] \
+        || mkdir -p "$ROOTDIR/${dst%/*}"
+
+  if cp -dpfPL "$src" "$ROOTDIR/$dst" \
+        && chown -h $owner "$ROOTDIR/$dst" \
+    && [ ! -L "$ROOTDIR/$dst" ]; then
+        chmod $perm "$ROOTDIR/$dst"
+  fi
+
+  [ -n "$FILE_LIST" ] && echo $dst >> $FILE_LIST
+}
+
+# usage: install-dir <owner> <perm> <dir>...
+#
+function install-dir {
+  local owner="$1" ; shift
+  local perm="$1" ; shift
+  local dst
+
+  for dst in "$@"; do
+    mkdir -pm $perm "$ROOTDIR/$dst" && chown -h $owner "$ROOTDIR/$dst"
+    [ -n "$FILE_LIST" ] && echo $dst >> $FILE_LIST
+  done
+}
+
+# usage: install-ln <owner> <target> <dest>
+#
+function install-ln {
+  local owner="$1" ; shift
+  local target="$1" ; shift
+  local dst="$1" ; shift
+
+  [ -n "${dst##*/*}" -o -d "$ROOTDIR/${dst%/*}" ] \
+      || mkdir -p "$ROOTDIR/${dst%/*}"
+
+  ln -snf "$target" "$ROOTDIR/$dst" \
+      && chown -h $owner "$ROOTDIR/$dst"
+
+  [ -n "$FILE_LIST" ] && echo $dst >> $FILE_LIST
+}
 
 #  
 # usage: set_perm uid:gid mode file...
@@ -604,31 +681,20 @@ function do_build_shared {
 
 # install package
 #
-# pkg install name [-p path] [-a archi]
+# pkg install name [[package_name|prf] installpath ]
 #  ex :
-#  pkg install openssh-4.7p1-flx1.1 -p /var/flx
+#  pkg install openssh-4.7p1-flx1.1  /var/toolchain/rootdir/
+#  pkg install filesystem.prf /var/toolchain/rootdir/
 #
 
 function do_install {
-
-  if [ "${1:0:1}" != "-" ]; then
-    shift
+  ARG1=$1
+  INSTALLPATH=$2
+  if [ "${ARG1##*.}" != "prf" ]; then
+    get_name "$ARG1" %L %P %D
+    EXACTPKG=$REPLY
+    echo "GET_NAME: ${REPLY} ${PKGDIR} ${EXACTPKG}"
   fi
-
-  while getopts "a:p:" OPTION; do
-    case $OPTION in
-        a)
-		INSTALLARCH=$OPTARG
-	;;
-        p)
-		INSTALLPATH=$OPTARG
-	;;
-    esac
-    if [ -z "$OPTARG" ]; then
-      echo "Bad arguments"
-      return 1
-    fi
-  done
 
 
   FLXARCH=${FLXARCH:-$INSTALLARCH}
@@ -644,19 +710,22 @@ function do_install {
 ## check dependencies and launch build of dependencies
 function do_deps {
  local arch
+  curpkg=$REPLY
   for dep in "${MAKEDEPENDS[@]}"; do
     get_name "${dep%%:*}" 
     name=$REPLY
     arch=${dep##*:}
+    if [ -z "$PKGDIR" ]; then
+      echo "Can't find dependencies ${dep%%:*}"
+      return 1
+    fi
     FILE=($PKGDIR/compiled/$name-$arch.$PKGSUFF)
     if [ -z "$FILE" ]; then
-      if [ -n "build_.$name" ]; then
-        ( mkdir -p "build_.${name}"
-	  echo "Package ${name}-$arch not found, preparing tree."
-          cd "build_.${name}"
-          pkg setpkg "${name}"
-          pkg deps ) || return $?
-      fi
+      DEPS=$($0 deps $name)|| exit $?
+      local OLDIFS=$IFS
+      IFS=' '
+      while read line; do echo "$PKGDIR|$arch:$line" ; done <<< $DEPS
+      IFS=$OLDIFS
     fi
   done
   return 0
@@ -710,6 +779,10 @@ function do_build {
 # desired one.
 # The resulting package name is returned in REPLY, and the package directory
 # is returned in PKGDIR whenever possible.
+#
+# The environnement variable PKG_NOCHOICE exit pkg if there isn't exact match
+#
+
 function get_name {
     local pattern pkg_name
     local radix ver build
@@ -724,7 +797,6 @@ function get_name {
 	    pattern="$(basename $CURDIR)"
 	elif [ "$pattern" = "%L" ]; then
 	    if [ -r "${LINKNAME}/${VERSFILE}" -a -s "${LINKNAME}/${VERSFILE}" ]; then
-	        echo "STEP 1"
 		REPLY="$(cat ${LINKNAME}/${VERSFILE})"
 		REPLY="${REPLY##*/}"
 		PKGDIR="$CURDIR/${LINKNAME}/."
@@ -763,10 +835,11 @@ function get_name {
 	    while [ "$pkg_name" -a -z "$rel_list" -a -z "$dev_list" ]; do
 		#rel_list=( $(find ${search_dir:+$search_dir/} $PKGROOT/ -maxdepth 2 -type f -path ${pkg_name}/build.cfg -printf "%h\n" 2>/dev/null) )
 		#rel_list=( ${search_dir:+$CURDIR} $(find $PKGROOT/ -maxdepth 2 -type f -path ${pkg_name}/build.cfg -printf "%h\n" 2>/dev/null) )
-		rel_list=( $(find ${search_dir:+$CURDIR/} $PKGROOT/ -maxdepth 2 -type f -path "*/${pkg_name}/build.cfg" -printf "%h\n" 2>/dev/null | uniq) )
-		for DIR in "${LISTPKGROOT[@]}"; do
-		  rel_list=( $(find ${search_dir:+$CURDIR/} $DIR/ -maxdepth 2 -type f -path "*/${pkg_name}/build.cfg" -printf "%h\n" 2>/dev/null | uniq) "${rel_list[@]}" )
-		done
+		rel_list=( $(find ${search_dir:+$CURDIR/} $PKGROOT/ ${LISTPKGROOT[*]} -maxdepth 2 -type f -path "*/${pkg_name}/build.cfg" -printf "%h\n" 2>/dev/null | uniq) )
+#		for DIR in ${LISTPKGROOT[@]}; do
+#			echo $DIR
+#		  rel_list=( $(find ${search_dir:+$CURDIR/} $DIR/ -maxdepth 2 -type f -path "*/${pkg_name}/build.cfg" -printf "%h\n" 2>/dev/null | uniq) "${rel_list[@]}" )
+#		done
 
 		if [ "$release_only" != "1" ]; then
 		    dev_list=( $(find $DEVROOT/ -maxdepth 2 -type f -path "*/${pkg_name}/build.cfg" -printf "%h\n" 2>/dev/null) )
@@ -810,6 +883,10 @@ function get_name {
 	    fi
 
 	    # now, we'll present the possible names to the user.
+	    if [ -n "$PKG_NOCHOICE" ]; then
+#	      echo "Can't find exact package $pattern" >&2
+	      return 1
+	    fi
 	    i=0
 	    printf " %5d : - None of the following packages -\n" 0
 	    while [ $i -lt ${#sort_list[*]} ]; do
@@ -847,7 +924,7 @@ function get_name {
 		    break;
 		elif [ $i -le ${#sort_list[*]} ]; then
 		    REPLY="${sort_list[$[$i-1]]}"
-		    PKGDIR="${REPLY/*}"
+		    PKGDIR="${REPLY}"
 		    REPLY="${REPLY##*/}"
 		    return
 		fi
@@ -1709,8 +1786,11 @@ function do_filesearch {
 
 # search packages
 function do_search {
-  echo "searching package '$1' in $PKGROOT..."
-  ls "$PKGROOT" | grep -i "$1"
+  if [ -n "$PKGDIR" ]; then
+    echo $PKGDIR
+  else
+    echo "ERROR:$1"
+  fi
 }
 
 # get package
@@ -1727,10 +1807,27 @@ function get_package {
 	  git clone "$1" src
 	;;
 	http)
-	  wget "$1"
+	  (  FILE=${1##*/} 
+	    wget -c "$1" -O "$FILE" || return 1
+	    if [ "${FILE##*.}" == "gz" ]; then
+	      tar xvfz $FILE || return 1
+	      cd ${FILE%%.tar.gz} || return 1
+	    else
+	      tar xvjf $FILE || return 1
+	      cd ${FILE%%.tar.bz2} || return 1
+	    fi
+	    mv * ..
+	   )
 	;;
 	ftp)
 	  wget "$1"
+	;;
+	file)
+	  if [ -e ".flxpkg" ]; then
+	    cp -a "$1"/* . 
+	  else
+	    cp -a "$1" .
+	  fi
 	;;
 	*)
 	  echo "$2 is not a good method of retrieval"
@@ -2279,7 +2376,7 @@ while [ $# -gt 0 ] ; do
 	    break
 	    ;;
 	*)
-	    if [ ${1:0:1} == '-' -a -z "${ARGLIST[*]}" ]; then  # allows usage of getopts
+	    if [ "${1:0:1}" == '-' -a -z "${ARGLIST[*]}" ]; then  # allows usage of getopts
 	      PRINTUSAGE=1
 	      break
 	    else
@@ -2324,9 +2421,9 @@ while [ $CHAINCMD -gt 0 -a ${#ARGLIST[@]} -gt 0 ]; do
 	install)
 	    CHAINCMD=0
 	    KNOWNCMD=1
-	    get_name ${ARGLIST[0]} %L %P
 	    ;;
 	search)
+	    get_name ${ARGLIST[0]}
 	    CHAINCMD=0
             KNOWNCMD=1
 	    ;;
@@ -2411,7 +2508,7 @@ while [ $CHAINCMD -gt 0 -a ${#ARGLIST[@]} -gt 0 ]; do
     [ $CHAINCMD -gt 0 ] && (echo;echo "===> PKG: starting [$ACTION] <===") >&2
 
     set +o noglob
-    if [ "$ACTION" != "newpkg" -a "$ACTION" != "search" -a "$ACTION" != "filesearch" ]; then
+    if [ "$ACTION" != "newpkg" -a "$ACTION" != "install" -a "$ACTION" != "search" -a "$ACTION" != "filesearch" ]; then
 	if [ -z "$REPLY" ]; then
 	    echo "Error: package name not found."
 	    exit 1
@@ -2440,7 +2537,7 @@ while [ $CHAINCMD -gt 0 -a ${#ARGLIST[@]} -gt 0 ]; do
     set_cross_environment
     set_compiler_options
 
-    if [ "$ACTION" != "newpkg" -a "$ACTION" != "search" -a "$ACTION" != "filesearch" ]; then
+    if [ "$ACTION" != "newpkg" -a "$ACTION" != "install" -a "$ACTION" != "search" -a "$ACTION" != "filesearch" ]; then
 	. $CFGFILE
     fi
 
@@ -2467,4 +2564,3 @@ done
 
 [ $CHAINCMD -gt 0 ] && (echo "===> PKG: [END] <===";echo) >&2
 exit 0
-
