scripts: pkg-cache: list all failed updates before quitting
It's inefficient and annoying to have to fix missing .repository in
packages one at a time instead of having the full list at once. Let's
list them all before failing.

diff --git a/scripts/pkg-cache b/scripts/pkg-cache
--- a/scripts/pkg-cache
+++ b/scripts/pkg-cache
@@ -75,6 +75,7 @@ function do_update() {
 	local repo
 	local newpackages
 	local new
+	local fail
 
 	if [ -z "$PKGCACHEDIR" ] ; then
 		echo "No destination, please specify PKGCACHEDIR" >&2
@@ -85,12 +86,19 @@ function do_update() {
 		echo "Unable to create $PKGCACHEDIR/" >&2
 		exit 1
 	fi
+
+	fail=0
 	for i in ${PKGCACHEDIR}/* ; do
 		if [ -d "$i" -a ! -e "$i/.repository" ] ; then
 			echo "$i package is missing .repository"
-			exit 1
+			fail=1
 		fi
 	done
+	if [ "$fail" != "0" ]; then
+		echo "Fatal: remove offending package(s) or add the missing .repository file."
+		exit 1
+	fi
+
 	chmod -R u+w ${PKGCACHEDIR}/* 2>/dev/null
 	for repopath in ${FLXREPOS} ; do
 		if ! rcmd test -d "$repopath/" ; then
