scripts/pkg-{filter,build} : detect all packages not found at once
It's almost impossible to work between two machines when reporting one
missing package at a time. Now instead of reporting a single error, we
report all missing packages at once, and only then we stop. This ensures
we can actually retrieve all missing packages from the remote machine
before trying to build again.

diff --git a/scripts/pkg-build b/scripts/pkg-build
--- a/scripts/pkg-build
+++ b/scripts/pkg-build
@@ -47,7 +47,7 @@ do_build() {
 
 	if [ "$#" -gt 0 ]; then
 		rm -f ${TMP_PACK}/allbuild.lpk
-
+		err=0
 		for i in "$@"; do
 			# retrieve optional architecture after ":" at the end of the name
 			arch="${DEFAULT_ARCH}"
@@ -75,10 +75,14 @@ do_build() {
 			elif [ -d "$PKGROOT/$i" ] ; then
 				ln -s $PKGROOT/$i $PKGFILTEREDDIR/$i
 			else
-				echo "Error: $i not found, your cache may not up to date try: ( pkg-cache update )" >&2
-				exit 1
+				echo "Error: $i not found, your cache may not be up to date try: ( pkg-cache update )" >&2
+				(( err++ ))
 			fi
 		done > ${TMP_PACK}/allbuild.lpk
+		if [ $err -gt 0 ]; then
+			echo; echo "$err error(s) found, exiting."
+			exit 1
+		fi
 	else
 		${FLXTECHNO}/scripts/pkg-filter update
 		[ $? -eq 0 ] || exit 1
diff --git a/scripts/pkg-filter b/scripts/pkg-filter
--- a/scripts/pkg-filter
+++ b/scripts/pkg-filter
@@ -33,21 +33,26 @@ function do_update() {
 	rm -f $PKGFILTEREDDIR/*
 
 	if [ -f "$PRJ_DIR/packaging/bld/formilux.bld" ]; then
+		err=0
 		${FLXTECHNO}/scripts/env-expand "$PRJ_DIR/packaging/lpk/"*.lpk > ${TMP_PACK}/allbuild.lpk
 		echo -n "Preparing $PKGFILTEREDDIR from formilux.bld..."
 		while read package trash ; do
 			if [ -d "$DEVROOT/$package" ] ; then
 				ln -s "$DEVROOT/$package" "$PKGFILTEREDDIR/" || echo " Maybe package $package appears twice ?" >&2
-				[ ! -d "$PKGROOT/$package" ] || { echo " error" ; echo "Error package $package is both in DEVROOT and PKGROOT, please fix conflict" >&2 ; exit 1 ; }
+				[ ! -d "$PKGROOT/$package" ] || { echo " error" ; echo "Error package $package is both in DEVROOT and PKGROOT, please fix conflict" >&2 ; (( err++ )) ; }
 			elif [ -d "$PKGROOT/$package" ] ; then
 				ln -s "$PKGROOT/$package" "$PKGFILTEREDDIR/" || echo " Maybe package $package appears twice ?" >&2
 			else
 				echo " error"
-				echo "Error $package not found, your cache may not up to date try: ( pkg-cache update )" >&2
-				exit 1
+				echo "Error: $package not found, your cache may not be up to date try: ( pkg-cache update )" >&2
+				(( err++ ));
 			fi
 			echo -n "."
 		done < "$PRJ_DIR/packaging/bld/formilux.bld"
+		if [ $err -gt 0 ]; then
+			echo; echo "$err error(s) found, exiting."
+			exit 1
+		fi
 		echo " success"
 	else
 		echo -n "Resolving versions from *.lpk to allbuild.tmp ..."
@@ -95,6 +100,7 @@ function do_update() {
 		echo "done."
 
 		echo "Creating links in $PKGFILTEREDDIR ... "
+		err=0
 		while read package archs rest ; do
 			if [ -n "${archs}" -a -z "${archs##build:*}" ]; then
 				continue
@@ -113,11 +119,15 @@ function do_update() {
 				ln -s "$PKGROOT/$package" "$PKGFILTEREDDIR/" || echo " Maybe package $package appears twice ?" >&2
 			else
 				echo " error"
-				echo "Error $package not found, your cache may not up to date try: ( pkg-cache update )" >&2
-				exit 1
+				echo "Error: $package not found, your cache may not be up to date try: ( pkg-cache update )" >&2
+				(( err++ ));
 			fi
 			echo -n "."
 		done < "${TMP_PACK}/allbuild.lpk" || exit $?
+		if [ $err -gt 0 ]; then
+			echo; echo "$err error(s) found, exiting."
+			exit 1
+		fi
 		echo " success"
 	fi
 
