* prepare-common-0.0.4 : accept multiple pkg-dirs

diff --git a/scripts/prepare-common b/scripts/prepare-common
--- a/scripts/prepare-common
+++ b/scripts/prepare-common
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# build/tools/prepare-common - prepare common files - version 0.0.3 - 2004-08-07
+# build/tools/prepare-common - prepare common files - version 0.0.4 - 2005-07-01
 # This file is part of the Formilux project : http://formilux.ant-computing.com/
 #
 # Copyright (C) 2001-2003 Benoit Dolez & Willy Tarreau
@@ -51,6 +51,7 @@ myname=$0
 PRINTUSAGE=0
 CLEAN_ONLY=0
 
+DIRLIST=( )
 while [ $# -gt 0 ] ; do
     case "$1" in 
         -c) # -c = clean
@@ -60,12 +61,21 @@ while [ $# -gt 0 ] ; do
             PRINTUSAGE=1
             shift
             ;;
+	-*) #
+	    echo "Unknown argument : $1"
+	    PRINTUSAGE=1
+	    shift
+	    ;;
+	*) # additional directory
+	    DIRLIST[${#DIRLIST[@]}]="$1"
+	    shift
+	    ;;
     esac
     shift
 done
 
 if [ $PRINTUSAGE -gt 0 ]; then
-    echo "Usage: ${myname##*/} [ -c ]"
+    echo "Usage: ${myname##*/} [ -c ] [ other_pkgdir... ]"
     echo "   will clean then rebuild the common parts between all media."
     echo "   If '-c' is set, then the tree will only be cleaned."
     exit 1
@@ -94,7 +104,7 @@ $TOOLS/mk-pkg common || die "There was an error rebuilding the links. Aborting."
 
 echo;echo "+++ Refreshing common packages (common/pkg)";echo
 #rm -f common/pkg/*
-$TOOLS/merge-pkg ../pkg || die "There was an error merging the packages. Aborting."
+$TOOLS/merge-pkg ../pkg "${DIRLIST[@]}" || die "There was an error merging the packages. Aborting."
 
 # Rem: no need to remove duplicates since we won't put these files on the medium.
 
