scripts: build-kernel-list: support compressing images
On ARM/ARM64, the image is often "Image" and it is not compressed. But
modern u-boot supports gzip, lzo, lzma and zstd, all of which bring nice
savings to the total image size. With this patch we permit the caller
to specify IMGCOMP= with a command to compress the image, and IMGEXT=
with the extension.

diff --git a/scripts/kernel/build-kernel-list b/scripts/kernel/build-kernel-list
--- a/scripts/kernel/build-kernel-list
+++ b/scripts/kernel/build-kernel-list
@@ -59,6 +59,7 @@ usage() {
     echo "       CC=$CC USRCC=$USRCC HOSTCC=$HOSTCC PARALLELCC=$PARALLELCC"
     echo "       ARCH=$USERARCH DEFAULT_ARCH=$DEFAULT_ARCH KEEPDIR=$KEEPDIR"
     echo "       MAKE=$MAKE BOOTIMG=$BOOTIMG PLATFORM=$PLATFORM"
+    echo "       IMGCOMP=$IMGCOMP IMGEXT=$IMGEXT"
     echo "Note: this script needs sudo during the install phase."
     echo "CC may be used to force a command (eg: \"distcc gcc\")."
     echo "USRCC may be used to force a different CC to build init."
@@ -87,6 +88,9 @@ MAKE=${MAKE:-make}
 BOOTIMG=${BOOTIMG:-bzImage}
 PLATFORM=${PLATFORM:-}
 KEEPDIR=${KEEPDIR:-}
+# image compression command (stdin/stdout) and extension
+IMGCOMP=${IMGCOMP:-}
+IMGEXT=${IMGEXT:-}
 
 mkdir -p $OUTPUTDIR || die 1 "Cannot create directory : $OUTPUTDIR"
 
@@ -495,10 +499,15 @@ for cfg in "$@"; do
 	    $_SUDO chown -R root:adm $subarchdir/boot
 	    $_SUDO chmod -R g-w,o-rwx $subarchdir/boot
 
+            # recompress kernel image
+	    if [ -n "$IMGCOMP" -a -n "$IMGEXT" ]; then
+		    $IMGCOMP < arch/${ARCH}/boot/$BOOTIMG > arch/${ARCH}/boot/$BOOTIMG.$IMGEXT
+	    fi
+
             # install kernel
-	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG .config System.map $bootdir >> $OUTPUTDIR/$log 2>&1; err=$?
+	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG${IMGEXT:+.$IMGEXT} .config System.map $bootdir >> $OUTPUTDIR/$log 2>&1; err=$?
 	    if [ $err -ne 0 ]; then
-		echo "######### cp $BOOTIMG .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
+		echo "######### cp $BOOTIMG${IMGEXT:+.$IMGEXT} .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
 		[ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
 		(( tot_err++ ))
 		continue
@@ -562,23 +571,27 @@ for cfg in "$@"; do
 
             echo "Building initramfs for all-in-one kernel" >>$OUTPUTDIR/$log
             "${MAKE_CMD[@]}" -j $PARALLELCC $BOOTIMG CONFIG_INITRAMFS_SOURCE=$PWD/initramfs </dev/null >>$OUTPUTDIR/$log 2>&1; err=$?
+            # recompress kernel image
+	    if [ -n "$IMGCOMP" -a -n "$IMGEXT" ]; then
+		    $IMGCOMP < arch/${ARCH}/boot/$BOOTIMG > arch/${ARCH}/boot/$BOOTIMG.$IMGEXT
+	    fi
 
             echo "Packaging all-in-one kernel" >>$OUTPUTDIR/$log
-	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG .config System.map $bootdir >> $OUTPUTDIR/$log 2>&1; err=$?
+	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG${IMGEXT:+.$IMGEXT} .config System.map $bootdir >> $OUTPUTDIR/$log 2>&1; err=$?
 	    if [ $err -ne 0 ]; then
-		echo "######### cp $BOOTIMG .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
+		echo "######### cp $BOOTIMG${IMGEXT:+.$IMGEXT} .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
 		[ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
 		(( tot_err++ ))
 		continue
 	    fi
 
 	    # let's build the signature file
-	    $_SUDO find $subarchdir/ -xdev \( -name $BOOTIMG -o -name .config -o -name System.map \) -printf "%P\n" | \
+	    $_SUDO find $subarchdir/ -xdev \( -name $BOOTIMG${IMGEXT:+.$IMGEXT} -o -name .config -o -name System.map \) -printf "%P\n" | \
 		sh -c "( cd $subarchdir && $_SUDO xargs flx sign --ignore-dot --no-depth)" \
 		>$OUTPUTDIR/kernel-${KPKG}-${BUILDVERSION}-allin1-$subarch.lst
 
 	    # let's build the tar.gz
-	    $_SUDO find $subarchdir/ -xdev \( -name $BOOTIMG -o -name .config -o -name System.map \) -printf "%P\n" | \
+	    $_SUDO find $subarchdir/ -xdev \( -name $BOOTIMG${IMGEXT:+.$IMGEXT} -o -name .config -o -name System.map \) -printf "%P\n" | \
 		$_SUDO tar -C $subarchdir --no-recursion -T - -vcf - 2>>$OUTPUTDIR/$log | \
 		${cmd_gzip} 2>/dev/null >$OUTPUTDIR/kernel-${KPKG}-${BUILDVERSION}-allin1-$subarch.tgz
 
@@ -587,11 +600,11 @@ for cfg in "$@"; do
 	    ;;
 	rh*)
 	    $_SUDO mkdir -p $subarchdir/boot
-	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG $subarchdir/boot/vmlinuz-$KVER >> $OUTPUTDIR/$log 2>&1 && \
+	    $_SUDO cp arch/${ARCH}/boot/$BOOTIMG${IMGEXT:+.$IMGEXT} $subarchdir/boot/vmlinuz-$KVER >> $OUTPUTDIR/$log 2>&1 && \
 	        $_SUDO cp .config $subarchdir/boot/config-$KVER >> $OUTPUTDIR/$log 2>&1 && \
 	        $_SUDO cp System.map $subarchdir/boot/System.map-$KVER >> $OUTPUTDIR/$log 2>&1; err=$?
 	    if [ $err -ne 0 ]; then
-		echo "######### cp $BOOTIMG .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
+		echo "######### cp $BOOTIMG${IMGEXT:+.$IMGEXT} .config System.map ... returned error code $err #########" | tee -a $OUTPUTDIR/$log
 		[ -z "$KEEPDIR" ] && $_SUDO rm -rf $destdir
 		(( tot_err++ ))
 		continue
